<?php
G::LoadClass("plugin");

class DemoPlugin extends PMPlugin
{
  
  
  public function DemoPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "Demo Plugin";
    $this->sDescription  = "Autogenerated plugin for class Demo";
    $this->sPluginFolder = "Demo";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerMenu("processmaker", "menuDemo.php");
    $this->registerMenu("cases", "menuCasesDemo.php");
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("Demo", __FILE__);
